name: AutoPilot
description: Report an issue with the AutoPilot feature or generated files
title: "[AUTOPILOT] <title>"
labels: Bug, Pending
assignees: Coopydood

body:
  - type: markdown
    attributes:
      value: |
       > [!NOTE]
       > This should be used only to report a bug relating to AutoPilot, or with the files it generates.

  - type: textarea
    id: autopilot-issue
    attributes:
      label: "Describe the Issue"
      description: Please describe your issue relating to **AutoPilot**.
      placeholder: Please describe your issue relating to AutoPilot.
    validations:
      required: true
      
  - type: textarea
    id: autopilot-reproduce
    attributes:
      label: "Reproduce the Issue"
      description: Describe how to accurately reproduce/exhibit the issue.
      placeholder: Please describe how to reproduce the issue.

  - type: textarea
    id: autopilot-expectation
    attributes:
      label: "Expectation"
      description: What did you expect to happen instead?
      placeholder: Please describe what you expected to happen.

  - type: markdown
    attributes:
      value: |
        ---
        # System Information

        Please enter your host system details to help contextualise the issue.

  - type: textarea
    id: systeminfo
    attributes:
      label: "System Specifications"
      description: Please provide details of your host system. The main points of interest are already filled in for you. Please replace the text in square brackets with the relevant information.
      placeholder: |
        **OS:** [OS name]
        **Kernel:** [full kernel version]
        **Processor:** [CPU model]
        **Memory:** [RAM installed in GBs]
        **Graphics:** [GPU models in use with the project, if any]
      value: |
        **OS: [OS name]
        **Kernel:** [full kernel version]
        **Processor:** [CPU model]
        **Memory:** [RAM installed in GBs]
        **Graphics:** [GPU models in use with the project, if any]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        # ultimate-macOS-KVM Information and logs

        Please enter the version of ULTMOS you are using, and any other relevant information.

  - type: input
    id: ultmos-version
    attributes:
      label: "Version"
      placeholder: vX.X.X
    validations:
      required: true

  - type: dropdown
    id: ultmos-branch
    attributes:
      label: "Branch"
      description: Please select the branch you are using.
      options:
        - main
        - dev
        - other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Log files and additional information

        Please provide the full contents of any generated files made by AutoPilot. You can drag & drop files into the text boxes to upload them.

        > [!NOTE]
        > AutoPilot log files can be found in the ``logs`` folder of the repo directory.

        > [!IMPORTANT]
        > Remember to redact any personal information, such as user names from file paths.

  - type: textarea
    id: autopilot-log-script
    attributes:
      label: "Generated Script File"
      placeholder: Please paste or drag & drop the contents of the script file generated by AutoPilot.
      render: shell
    validations:
      required: true

  - type: textarea
    id: autopilot-log-xml
    attributes:
      label: "Generated XML File (if applicable)"
      placeholder: Please paste or drag & drop the contents of the XML file generated by AutoPilot.
      render: xml

  - type: textarea
    id: autopilot-log-main
    attributes:
      label: "Generated Log File"
      placeholder: Please paste or drag & drop the contents of the log file generated by AutoPilot.
      render: bash
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: Please provide any additional information you think may be relevant.

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue. Please review the information you have provided and ensure it is correct before submitting the issue.