name: macOS
description: Report macOS issues unique to ULTMOS usage
title: "[macOS] "
labels: Bug, Pending
assignees: Coopydood

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > This should be used only to report a bug when running macOS **using ULTMOS**.

  - type: textarea
    id: macos-issue
    attributes:
      label: "Describe the Issue"
      description: Please describe your issue relating to **macOS** running under ULTMOS.
      placeholder: Please describe your issue relating to macOS running under ULTMOS.
    validations:
      required: true

  - type: textarea
    id: macos-reproduce
    attributes:
      label: "Reproduce the Issue"
      description: Describe how to accurately reproduce/exhibit the issue.
      placeholder: Please describe how to reproduce the issue.

  - type: textarea
    id: macos-expectation
    attributes:
      label: "Expectation"
      description: What did you expect to happen instead?
      placeholder: Please describe what you expected to happen.

  - type: textarea
    id: macos-screenshots
    attributes:
      label: "Screenshots"
      description: If available, please add some screenshots showing the issue.
      placeholder: Please paste/drag & drop screenshots regarding the issue.


  - type: markdown
    attributes:
      value: |
        ---
        # System Information

        Please enter your host system details to help contextualise the issue.

  - type: input
    id: host-os
    attributes:
      label: "Operating System"
    validations:
      required: true

  - type: input
    id: host-kernel
    attributes:
      label: "Kernel"
    validations:
      required: true

  - type: input
    id: host-cpu
    attributes:
      label: "Processor"
    validations:
      required: true
  
  - type: input
    id: host-ram
    attributes:
      label: "RAM (in GB)"
    validations:
      required: true

  - type: input
    id: host-gpu
    attributes:
      label: "GPU(s)"


  - type: markdown
    attributes:
      value: |
        ---
        # ultimate-macOS-KVM Information and logs

        Please enter the version of ULTMOS you are using, and any other relevant information.

  - type: input
    id: ultmos-version
    attributes:
      label: "Version"
      placeholder: vX.X.X
    validations:
      required: true

  - type: dropdown
    id: ultmos-branch
    attributes:
      label: "Branch"
      description: Please select the branch you are using.
      options:
        - main
        - dev
        - other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Log files and additional information

        If your issue occurs during or after running AutoPilot (either with AutoPilot itself or a file generated by it), please provide the relevant info shown below.

        > [!NOTE]
        > AutoPilot log files can be found in the ``logs`` folder of the repo directory.

        > [!IMPORTANT]
        > Remember to redact any personal information, such as user names from file paths.

  - type: textarea
    id: autopilot-log-script
    attributes:
      label: "Generated Script File"
      placeholder: Please paste or drag & drop the contents of the script file generated by AutoPilot.
      render: shell

  - type: textarea
    id: autopilot-log-xml
    attributes:
      label: "Generated XML File (if applicable)"
      placeholder: Please paste or drag & drop the contents of the XML file generated by AutoPilot.
      render: xml

  - type: textarea
    id: autopilot-log-main
    attributes:
      label: "Generated Log File"
      placeholder: Please paste or drag & drop the contents of the log file generated by AutoPilot.
      render: bash

  - type: markdown
    attributes:
      value: |
        ---

  - type: textarea
    id: additional
    attributes:
      label: "Additional Information"
      description: Please provide any additional information you think may be relevant.

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue. Please review the information you have provided and ensure it is correct before submitting the issue.
